### ISSUE TITLE
Amy doesn't respond to her name

### ISSUE THREAD

**Issue by Kwstubbs** [gideontong/Amy#1]
i think shes retarded

**Comment by brilam8** [comment]
+1 kwstubbs makes a very good point. i thought amy was an intelligent discord bot

**Comment by gideontong** [comment]
Agree, this is important issue.

**Comment by gideontong** [comment]
Added in commit 6849dc0e574b8c77a3df80bf7ed9fc468d91ec4f and live instantly via hotfix. Amy currently replies to you with a 1/20 chance, but will only ask you if you called her. More responses coming soon!

**Comment by gideontong** [comment]
Considering this feature resolved and closed with MAJORVERSION-2 release. See commit 1f964fc741ec9ecad2c2bc753eaa6dac13565ad9 for more information.
