### ISSUE TITLE
Amy should be able to pinpoint Leo's location at any given moment

### ISSUE THREAD

**Issue by oscillatingneutrino** [gideontong/Amy#10]

**Comment by gideontong** [comment]
Before I add this to the work tracker, is there something specific you had in mind? Like the ability to ask Amy where Leo is?

**Comment by gideontong** [comment]
Added as `!locate` command in commit 8c4374241db85673d7a3031d1191a3bc67edd857 and fully tested in commit 1f42fd7ee3930fe7db8e20286c1c2edcf5539802. Marking as resolved.
