### ISSUE TITLE
Amy should be able to open Leo's webcam and livestream whatever it is he is doing

### ISSUE THREAD

**Issue by oscillatingneutrino** [gideontong/Amy#16]

**Comment by gideontong** [comment]
This is unlikely to ever manifest as a feature. Keeping open for now.

**Comment by oscillatingneutrino** [comment]
Hi
Dont take my requests too seriously, I just add them to follow rule 3

**Comment by gideontong** [comment]
Sounds good. Closing issue. Don’t forget to tag Leo next time with @Leo10250
