### ISSUE TITLE
Every time Leo deletes an image, an image of him gets sent into the chat

### ISSUE THREAD

**Issue by oscillatingneutrino** [gideontong/Amy#5]

**Comment by gideontong** [comment]
Can you provide some pictures so they can be added to the bot?

**Comment by gideontong** [comment]
Code added detect when Leo deletes an image in commit 2d417be8261dc25d3c0e6f3a0fea39781b414286. Images of him are needed to enable this feature.

**Comment by mbuyd** [comment]
Is the LLD not large enough?

**Comment by gideontong** [comment]
Done. See the full commit at commit 6fcaa2e72949e856eb0803a90e58dd4dcb891698. It was good enough as @mbuyd said.

**Comment by gideontong** [comment]
Closing this issue because [RELEASE-v1.1.0](https://github.com/gideontong/Amy/releases/tag/v1.1.0) addresses this issue and resolves it.
