### ISSUE TITLE
Amy occasionally confuses English for Chinese

### ISSUE THREAD

**Issue by mbuyd** [gideontong/Amy#6]
For an artificially intelligence, Amy isn't that intelligent. I recommend teaching her the basics of English using [https://github.com/mbuyd/Text-generator](url), since that systems seems to work flawlessly.

**Comment by gideontong** [comment]
Removed comments about understanding Chinese in commit 23dc93e4066a2cdaab8fdf09b27307ad325965a4.

**Comment by gideontong** [comment]
Considering this feature resolved and closed with MAJORVERSION-2 release. See commit 1f964fc741ec9ecad2c2bc753eaa6dac13565ad9 for more information.
