### ISSUE TITLE
Amy should track the amount of time Leo spends on chrome

### ISSUE THREAD

**Issue by oscillatingneutrino** [gideontong/Amy#8]

**Comment by gideontong** [comment]
No guarantee this will become a feature unless you want the amount of time Leo has his Discord status set to Chrome?

**Comment by Leo10250** [comment]
She shouldn't

**Comment by gideontong** [comment]
Interesting comment from @Leo10250. Which will it be?

**Comment by gideontong** [comment]
The current meta has changed, and as such this issue will be closed without being complete. If it becomes viable again, please reopen this issue or create a new one referencing this issue.
