### ISSUE TITLE
amy should track number of "ehhh" leo types

### ISSUE THREAD

**Issue by brilam8** [gideontong/Amy#9]
maybe we can get statistics of the number of ehhh's typed according to how many h's there are and then calculate the average number of h's in a leo "eh"

**Comment by Leo10250** [comment]
NO

**Comment by gideontong** [comment]
As @Leo10250 proposed, he can handwrite this himself?

**Comment by brilam8** [comment]
good idea

**Comment by gideontong** [comment]
Ok @Leo10250 since I am in agreement with @brilam8 it has been agreed that you will be the storage medium.

**Comment by gideontong** [comment]
Implemented in commit 7354d881be49a14e1f7ec93ce423885ab1c1ea2b. Feature goes live in the next few hours.
